#äº®æš—ä¸»é¢˜
mode: auto

#å¤´åƒ
avatar:
  url: /images/avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹æƒ…å³å°†å‘ç”Ÿ

#é“¾æ¥
social:
  - name: GitHub
    link: https://github.com/QAQgc
    icon: icon-github-line
    color: "#181717"
  - name: E-Mail
    link: qaqgcc@google.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/23420632
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: Twitter
    link: https://twitter.com/QAQgc
    icon: icon-twitter-line
    color: "#1da1f2"

#å°é¢æ ‡é¢˜
banner:
  enable: true
  title: é¦†é•¿çš„å°ç«™
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

#å°æ ‡è¯­
notice:
  enable: true
  content: æ„Ÿè°¢ä½ æ¥åˆ°è¿™

#éšæœºå¤šè¾¹å½¢èƒŒæ™¯
# trianglify:
#   enable: false
#   cellSize: 75
#   width: 800
#   height: 600
#   palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
#   opacity: 0.5

#é¼ æ ‡æŒ‡é’ˆ
cursor:
  enable: true

#èƒŒæ™¯
bg_image:
  enable: true
  url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg
  dark: /images/dark_background.jpg
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

#æœç´¢èƒŒæ™¯
# search:
#   modal: true
#   bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
#   dark_bg_image: xxx
#   # placeholder:

#ä¸»é¢˜è‰²
# colors:
#   primary: "#ff0000"
#   # primary: "#6200ee"
#   bg: "#757575"
#   selection_bg: "#ff0000"
#   tag_start_color: "#999999"
#   tag_end_color: "#0078E7"
#   dark:
#     block: "#1b1f2e"
#     # block: "#17202A"

#ç½‘ç«™å›¾æ ‡
favicon: /favicon.png

#æ‰“èµ
reward:
  enable: false

#æ ‡ç­¾æ ·å¼
wordcloud:
  enable: true

#é¡µè„š
footer:
# since: 2016

  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
    url: http://www.4399.com/
    title: 4399
  
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2019-04-12T00:00:00"

#è¯„è®º
# comment:
#   enable: true
#   tips:
#     - è¯„è®ºåŒºæ–½å·¥ä¸­
#   # candidates:
#   #   - waline

#æœç´¢
engine_search:
  enable: false

# search
# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true
  src: /js/search/local-search.js